<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/* Require user to be admin */

/**
 * Middleware 'Admin' group
 */
Route::middleware(['admin'])->group(function(){

    // create a new post
    Route::get('posts/create','Posts\PostsController@create');
    // save the new post
    Route::post('posts','Posts\PostsController@store');
    // edit a post
    Route::get('posts/edit/{post}','Posts\PostsController@edit');
    // submit the edit form
    Route::put('posts','Posts\PostsController@update');
    // delete the post
    Route::delete('posts/delete/{post}', 'Posts\PostsController@destroy');

});
/* End of routes for user admin */

/* Using middleware Auth */

/**
 * Store a Comment in a Post
 */
Route::post('posts/comment','Posts\CommentsController@store')
            ->middleware('auth');


/*
// Using the middleware route by route
// .. ->middleware('admin')

// create a new post
Route::get('posts/create','Posts\PostsController@create')
            ->middleware('admin');
// save the new post
Route::post('posts','Posts\PostsController@store')
            ->middleware('admin');

// edit a post
Route::get('posts/edit/{post}','Posts\PostsController@edit')
            ->middleware('admin');
// submit the edit form
Route::put('posts','Posts\PostsController@update')
            ->middleware('admin');
// end adding a middleware by route
*/


/**
 * Routes without middleware
 * Accessible without login / authentication process
 */
Route::get('posts/{post}','Posts\PostsController@show');

Route::get('/', function () {
    return view('welcome');
});

Route::get('posts', 'Posts\PostsController@index')->name('posts');

Route::get('/posts/category/{category}','Posts\CategoriesController@index');

Route::get('/posts/tag/{tag}','Posts\TagsController@index');

/**
 * Code generated by `php artisan auth`
 */
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
